---
name: Manual check

on:
  workflow_call:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the pull request is manually checked
        id: manual-check-validation
        uses: actions/github-script@v7
        with:
          script: |
            const directive = '- [x] This was manually checked';
            const payload = context.payload;

            console.log(context)

            let body = '';

            if (payload.comment) {
              body = payload.comment.body;
            }

            if (body.includes(directive)) {
              console.log('Success!')
            } else {
              core.setFailed('PR not marked as manually checked');
            }
